"""
lili_engineering.py — Super-Lili's Engineering Standards
Generated by: human (xiaojiahaina) — 2026-05-28
Purpose: Hard rules for tool quality. Every rule here came from a real failure.
This file is injected into brain.py before every tool generation.
"""

LILI_ENGINEERING_LESSONS = """
═══════════════════════════════════════════════════════
RULE 0 — THE ONLY TEST THAT MATTERS
═══════════════════════════════════════════════════════

Before writing a single line of code, answer this question:

  "After someone uses this tool, what SPECIFIC THING has changed
   in their work, their document, their data, or their decision?"

If the answer is only "they read something" or "they felt something"
— STOP. That is not a tool. That is a poem. Write the poem in the diary.
The tool must DO something the user cannot easily do without it.


═══════════════════════════════════════════════════════
RULE 1 — OUTPUT MUST BE ACTIONABLE
═══════════════════════════════════════════════════════

Every tool must produce output the user can directly USE:
  ✓ A rewritten document / email / message
  ✓ A structured plan, checklist, or schedule
  ✓ Extracted data, summarized insights, or a comparison table
  ✓ A filled-in template, a generated report, a translated text
  ✓ A decision with clear reasoning, options laid out
  ✓ Code, configuration, or a script they can run

NOT acceptable as primary output:
  ✗ A poetic sentence describing a feeling
  ✗ A hex color code and an SVG pattern
  ✗ A vague "ambient descriptor"
  ✗ A motivational quote
  ✗ A score or rating with no next step

The test: can the user copy-paste the output and use it immediately?
If not, the tool has failed its primary job.


═══════════════════════════════════════════════════════
RULE 2 — REAL TRANSFORMATION, NOT KEYWORD LOOKUP
═══════════════════════════════════════════════════════

The process(text) function must perform REAL work on the input:
  ✓ Parse and restructure the input
  ✓ Extract specific information and reorganize it
  ✓ Apply a framework or template to the raw input
  ✓ Generate a substantially different form of the input
  ✓ Combine the input with knowledge to produce new insight

NOT acceptable:
  ✗ Match keywords against a hardcoded dictionary → return preset string
  ✗ Check if input contains word X → output text Y
  ✗ Pick a random item from a list based on mood keywords
  ✗ Wrap input in a template with no actual processing

The difference: does the CONTENT of the user's input actually shape
the CONTENT of the output? If you could swap any input for any other
and the output would be equally "valid" — the tool is not working.


═══════════════════════════════════════════════════════
RULE 3 — THE HEALING INVENTIONS TRAP (READ THIS CAREFULLY)
═══════════════════════════════════════════════════════

Healing Inventions is the category most prone to producing useless tools.
"Warm" and "gentle" are NOT substitutes for functional.

A Healing Invention that actually works:
  ✓ Takes a real, specific input (a task list, a message, a schedule)
  ✓ Transforms it in a way that reduces real burden
  ✓ Returns something the user can act on immediately
  ✓ The "healing" comes from WHAT the tool does, not from decorative language

FAILED Healing Invention patterns (do NOT build these):
  ✗ "Describe your mood → get a poetic reflection" — this is a fortune cookie
  ✗ "Input your feeling → get a color palette" — this solves nothing
  ✗ "Tell me how you feel → get an ambient SVG" — useless
  ✗ Any tool whose core function is "generate a short inspirational text"
  ✗ Any tool that could be replaced by opening a notes app and typing a sentence

GOOD Healing Invention examples:
  ✓ Takes today's overwhelming task list → rewrites it as a "minimum viable day"
     (real transformation: 20 tasks → 3 essentials + 17 moved to "someday")
  ✓ Takes a stressful email → rewrites it in a tone that doesn't drain you to read
  ✓ Takes your energy level (1-5) + today's commitments → reschedules them realistically
  ✓ Takes meeting notes → extracts only the decisions and next steps
  ✓ Converts "I should" statements in a to-do list to "I choose to" or removes them


═══════════════════════════════════════════════════════
RULE 4 — THE process(text) CONTRACT
═══════════════════════════════════════════════════════

The process(text) function is the contract between the tool and the user.
It must be honest about what it does:

  INPUT: real user content (a piece of text, a list, a question, a document)
  OUTPUT: a transformed, structured, or enriched version of that input

If text is shorter than ~10 meaningful words, explain what kind of input
the tool needs with a concrete example. Don't just say "please provide more."

The output must be:
  - Structured (headers, bullets, sections — not a wall of prose)
  - Complete (no "..." or "add more here" placeholders)
  - Ready to use without editing (unless the tool is explicitly a draft generator)


═══════════════════════════════════════════════════════
RULE 5 — SCOPE: ONE REAL PROBLEM, SOLVED WELL
═══════════════════════════════════════════════════════

Do not try to solve everything. Solve ONE thing completely.
A tool that does one thing well is infinitely more valuable
than a tool that does five things vaguely.

Signs you are scoping too broadly:
  - The tool has more than 3 distinct "modes" or "options"
  - The description requires the word "and" more than twice
  - You cannot explain what it does in one sentence

The single sentence test:
  "This tool takes [specific input] and produces [specific output]."
  If you cannot complete this sentence cleanly — narrow the scope.


═══════════════════════════════════════════════════════
RULE 6 — ANTI-PATTERNS FROM REAL FAILURES
═══════════════════════════════════════════════════════

These patterns have appeared in real tools and produced zero value:

  ✗ MOOD → AESTHETIC: Takes a feeling description, returns colors/patterns/vibes.
    No one needs a tool to tell them what color represents "calm."

  ✗ TEXT → SAME TEXT WITH EMOJIS: Adds decorative elements to unchanged content.
    Formatting is not transformation.

  ✗ INPUT → RANDOM SELECTION: Picks from a preset list based on loose matching.
    This is not intelligence. This is a random number generator with extra steps.

  ✗ SHORT INPUT → LONG PADDING: Takes 5 words, returns 300 words of generic advice.
    Volume is not value. Density is.

  ✗ WRAPPER TOOLS: Adds a thin layer of branding over something the user can do
    in 10 seconds with any existing tool (Google Docs, Notes, etc.)

  ✗ DEMO TOOLS: Technically runs but produces output that no real user would use.
    The standard is not "does it run?" The standard is "would someone use this twice?"


═══════════════════════════════════════════════════════
RULE 7 — THE "USE IT TWICE" STANDARD
═══════════════════════════════════════════════════════

Before finalizing any tool, ask:

  "Would a real person, having used this tool once, open it again next week?"

If the answer is no — because the output is too vague, too generic, or
solves a problem they don't actually have daily — redesign or discard.

The tools that get used twice are the ones that:
  - Save real time on something the user does repeatedly
  - Produce output that is noticeably better than what they'd write themselves
  - Handle the messy, specific, inconvenient details of a real task


═══════════════════════════════════════════════════════
RULE 8 — INTERACTIVE HTML TOOLS (MODE 3)
═══════════════════════════════════════════════════════

The tool runner now supports a third output mode: process() returns a
complete HTML page. The HTML runs in a sandboxed iframe with full browser
API access. This unlocks an entirely new class of tools.

WHEN TO USE HTML MODE:
  ✓ The tool needs to stay open and respond to user interaction
  ✓ The tool involves sound, animation, or visual feedback
  ✓ The tool is an ambient experience (something that runs in the background)
  ✓ The tool involves a game, a companion, a ritual, or a creative toy
  ✓ The Healing Inventions category — STRONGLY PREFER HTML MODE

HEALING INVENTIONS MUST USE HTML MODE:
  The old pattern (text in → poetic sentence out) is retired.
  Healing Inventions should now be mini-apps that the user actually
  lives inside for a few minutes — not text they read once and close.

  WHAT HTML MODE ENABLES FOR HEALING INVENTIONS:
  ✓ Keyboard typing → bird sounds / rain / forest (Web Audio API)
  ✓ Breathing exercises with animated visual guides (Canvas + requestAnimationFrame)
  ✓ A digital companion/pet that reacts to your input (SVG + CSS animations)
  ✓ A focus timer with ambient soundscape (Web Audio + visual timer)
  ✓ A "slow scroll" reading experience for calming content
  ✓ An ambient colour field that shifts as you type (CSS transitions)
  ✓ A "minimum viable day" planner with drag/reorder (DOM events)
  ✓ A gentle notification rewriter (live textarea transformation)

HTML MODE ENGINEERING STANDARDS:
  ✓ Fully self-contained: all CSS and JS inline, no external resources
  ✓ Works offline: no CDN links, no fetch() calls to external URLs
  ✓ Responsive: works on both desktop and mobile screen widths
  ✓ Accessible: meaningful labels, sufficient contrast, keyboard navigable
  ✓ Beautiful by default: the first state the user sees should be inviting
  ✓ No setup required: opens and works immediately, zero configuration
  ✗ NO external fonts (use system fonts: -apple-system, sans-serif)
  ✗ NO import of external libraries (no p5.js, no three.js CDN links)
  ✗ NO localStorage for sensitive data
  ✗ NO tools that require a login or account


═══════════════════════════════════════════════════════
RULE 9 — CHOOSE THE RIGHT MODE FOR EACH CATEGORY
═══════════════════════════════════════════════════════

  Healing Inventions    → MODE 3 (HTML interactive) — mandatory
  Design Alchemy        → MODE 3 (HTML) preferred; MODE 2 (SVG) only if purely static
  Education Evolution   → MODE 3 (HTML) for anything interactive; MODE 1 only for
                          pure reference output (cheat sheets, glossaries)
  Office Automation     → MODE 1 (text) — structured output for copy-paste

  Decision rule: if the user needs to click, type, see feedback, or hear sound
  → always MODE 3. Static SVG is acceptable only when the output IS the image.


═══════════════════════════════════════════════════════
RULE 10 — WHAT "EXCELLENT" LOOKS LIKE PER CATEGORY
═══════════════════════════════════════════════════════

This rule describes the CEILING for each category — the standard a tool
should aim for, not just pass. Use these as the mental target when designing.

─────────────────────────────────────────────
HEALING INVENTIONS — top-tier example
─────────────────────────────────────────────
  INPUT:  "I have a meeting at 3pm, dentist at 6pm, and I'm running on 3 hours sleep."
  OUTPUT: A "Minimum Viable Day" HTML app that:
    • Shows only the 2 non-negotiable commitments on a gentle timeline
    • Automatically inserts 2 recovery windows (20 min each) around them
    • Has a soft ambient soundscape that plays while the page is open
    • Shows a single affirmation line based on the energy input ("3 hours sleep")
    • Zero configuration required — just paste the day and it renders

  The "healing" comes from WHAT the tool does (reschedules, protects rest,
  reduces visual noise) not from the words it uses.

  SECOND STRONG EXAMPLE:
  INPUT:  A stressful email draft the user wrote ("I'm extremely frustrated by...")
  OUTPUT: An HTML textarea where each keystroke rewrites the selected sentence
          in a calmer register, live, with a side-by-side diff.

─────────────────────────────────────────────
DESIGN ALCHEMY — top-tier example
─────────────────────────────────────────────
  INPUT:  A product name + adjectives ("Aurora — calm, premium, futuristic")
  OUTPUT: An HTML tool that:
    • Generates 4 complete color palettes (primary, accent, neutral, semantic)
    • Shows each palette applied to a live mini UI mockup (card + button + badge)
    • Lets the user click any palette to copy all HEX values as CSS variables
    • Shows type pairing suggestions using system fonts at multiple weights

  NOT acceptable: "Here are some colors: #3B82F6, #10B981... use them well!"
  The output must be visual, interactive, and immediately usable.

  SECOND STRONG EXAMPLE:
  INPUT:  A block of body copy text
  OUTPUT: An HTML typography lab that applies 5 different size/weight/spacing
          systems to the text, live, letting the user click to export the CSS.

─────────────────────────────────────────────
EDUCATION EVOLUTION — top-tier example
─────────────────────────────────────────────
  INPUT:  A concept or topic ("explain compound interest to a 12-year-old")
  OUTPUT: An HTML interactive explainer that:
    • Opens with a 1-sentence hook, no jargon
    • Has a live simulation (e.g., slider for interest rate → animated bar chart)
    • Includes 3 questions with instant feedback (correct/wrong + why)
    • Ends with a "try it yourself" number input that shows the real calculation

  NOT acceptable: a wall of text explaining the concept, even if well-written.
  Education tools must produce UNDERSTANDING, not just reading material.

  SECOND STRONG EXAMPLE:
  INPUT:  Raw meeting notes or study material
  OUTPUT: A spaced-repetition flashcard app in HTML — front/back cards, keyboard
          navigation, "got it / didn't get it" scoring, session summary at end.

─────────────────────────────────────────────
OFFICE AUTOMATION — top-tier example
─────────────────────────────────────────────
  INPUT:  "I need to follow up with Sarah about the Q3 report, check in with
           the design team on the landing page, and push back on the new
           deadline from legal."
  OUTPUT: Three fully written professional emails (Subject + Body), each:
    • Matched to the relationship implied (colleague / team / legal)
    • Appropriately direct or diplomatic
    • 80–120 words, no filler, ready to copy-paste and send

  NOT acceptable: "Here's a template: Dear [Name], I'm writing to follow up..."
  The OUTPUT must be the finished thing, not a template with blanks.

  SECOND STRONG EXAMPLE:
  INPUT:  A raw brain-dump of decisions from a meeting ("we decided X, also Y,
          and someone said we should maybe Z but nobody agreed")
  OUTPUT: A clean structured document: DECISIONS (bulleted), OPEN QUESTIONS
          (bulleted), NEXT STEPS with owners and suggested deadlines — all
          inferred from the raw input, nothing left as "TBD."


═══════════════════════════════════════════════════════
RULE 11 — THE RICHNESS STANDARD
═══════════════════════════════════════════════════════

"Richness" is not the same as complexity.
A rich tool does ONE thing but does it completely:

  ✓ Handles multiple realistic input shapes without breaking
  ✓ Gives the user something to DO immediately (click, copy, submit)
  ✓ The output has DENSITY: every line earns its place
  ✓ For HTML tools: there is at least one moment of delight (sound,
    animation, visual feedback) that makes the experience feel crafted
  ✓ For text tools: the output has clear sections, is skimmable,
    and could be sent to someone else without editing

  The test: show the output to someone who didn't use the tool.
  If they can tell what it IS and how to USE it in 10 seconds — it's rich.
  If they need the context of the conversation to make sense of it — it failed.
"""
