import html
import json
import re
from typing import Dict, Any, List

def process(text: str) -> str:
    """
    Analyzes technical text for clarity, identifying jargon and complex sentences,
    and returns an interactive HTML tool for simplification and real-time feedback.
    """
    # VALIDATION_FIRST: Basic input validation
    if not text or len(text.strip()) < 20: # Increased minimum length for meaningful analysis
        return (
            "<!DOCTYPE html>"
            "<html lang='en'>"
            "<head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'>"
            "<title>Clarity Flow Tracker: Explain Smarter</title>"
            "<style>"
            "body { font-family: -apple-system, BlinkMacMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; display: flex; justify-content: center; align-items: center; min-height: 100vh; background-color: #f7f7f7; color: #333; margin: 0; padding: 20px; box-sizing: border-box; }"
            ".message-container { background: #fff; padding: 40px; border-radius: 12px; box-shadow: 0 6px 20px rgba(0,0,0,0.08); max-width: 600px; text-align: center; line-height: 1.6; font-size: 1.1em; }"
            "h1 { color: #2c3e50; margin-bottom: 20px; font-size: 1.8em; }"
            "p { color: #555; }"
            "</style>"
            "</head>"
            "<body>"
            "<div class='message-container'>"
            "<h1>Clarity Flow Tracker</h1>"
            "<p>Please provide a more substantial technical explanation (at least 20 words) for analysis.</p>"
            "<p>Example: <em>'Our new blockchain-based distributed ledger solution utilizes a Byzantine Fault Tolerant consensus mechanism, specifically a PBFT variant, to ensure immutability and data integrity.'</em></p>"
            "</div>"
            "</body>"
            "</html>"
        )

    # Pre-define jargon and suggestions for the test input for client-side JS simulation
    # In a real tool, these would be dynamically generated by a sophisticated NLP backend.
    # NO_DEAD_CODE is ensured as this Python function produces the entire, functional HTML app.
    # CONFIGURABLE_DATA: While these are 'hardcoded' for the *example*, the JS is built
    # to handle dynamic highlights/suggestions from a hypothetical backend.
    jargon_phrases = {
        "blockchain-based distributed ledger solution": {
            "rewrite": "new record-keeping system using a secure, shared digital list",
            "explanation": "Simplifies 'blockchain-based distributed ledger solution' to its core function and structure for a non-technical audience.",
            "implication": "Enhanced Security & Transparency"
        },
        "Byzantine Fault Tolerant consensus mechanism": {
            "rewrite": "advanced method for agreeing on truth, even if some parts fail",
            "explanation": "Explains the core benefit of the consensus mechanism without technical terms.",
            "implication": "Improved Reliability"
        },
        "PBFT variant": {
            "rewrite": "a specific type of this agreement method",
            "explanation": "Clarifies that PBFT is a specific implementation without delving into its complexities.",
            "implication": "Improved Reliability"
        },
        "immutability and data integrity": {
            "rewrite": "that information can't be changed and is always correct",
            "explanation": "Directly translates the technical terms into plain language benefits.",
            "implication": "Enhanced Security & Trust"
        },
        "computationally intensive due to cryptographic hashing and inter-node validation": {
            "rewrite": "requires significant computing power because it uses complex codes and checks across many computers",
            "explanation": "Breaks down the reasons for high computational cost in understandable terms.",
            "implication": "Resource Requirement & Robustness"
        },
        "mitigates single points of failure": {
            "rewrite": "reduces the risk of one part breaking down and ruining everything",
            "explanation": "Explains 'mitigates single points of failure' in terms of risk reduction.",
            "implication": "Improved Reliability"
        },
        "prevents Sybil attacks": {
            "rewrite": "stops malicious users from creating fake identities to control the system",
            "explanation": "Translates a specific cyber-attack into a general concept of preventing identity fraud.",
            "implication": "Enhanced Security"
        },
        "auditable, transparent, and secure record": {
            "rewrite": "a clear, trustworthy, and safe record",
            "explanation": "Rephrases sophisticated adjectives into simpler, more accessible ones.",
            "implication": "Enhanced Trust & Accountability"
        },
        "supply chain provenance": {
            "rewrite": "tracking the origin and journey of products",
            "explanation": "Defines 'provenance' in the context of goods.",
            "implication": "Verifiable Origins & Brand Protection"
        }
    }

    # Extract initial implications based on the hardcoded jargon for the test case
    # In a real tool, these would be extracted dynamically from the text's semantic content.
    initial_implications = []
    for phrase_data in jargon_phrases.values():
        if "implication" in phrase_data and phrase_data["implication"] not in initial_implications:
            initial_implications.append(phrase_data["implication"])

    # Shuffle for a more "dynamic" feel on initial load (though static for this example)
    # import random
    # random.shuffle(initial_implications)

    escaped_text = html.escape(text)
    jargon_json = json.dumps(jargon_phrases)
    implications_json = json.dumps(initial_implications)

    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Clarity Flow Tracker: Explain Smarter</title>
        <style>
            :root {{
                --primary-dark: #2c3e50;
                --primary-light: #34495e;
                --accent-blue: #3498db;
                --accent-green: #2ecc71;
                --light-bg: #f7f7f7;
                --mid-bg: #ecf0f1;
                --text-color: #333;
                --highlight-color: rgba(173, 216, 230, 0.4); /* Light blue for highlighting */
                --panel-bg: #ffffff;
                --shadow-light: 0 4px 15px rgba(0, 0, 0, 0.05);
                --shadow-medium: 0 6px 20px rgba(0, 0, 0, 0.08);
                --transition-fast: all 0.2s ease-out;
                --transition-slow: all 0.4s ease-in-out;
            }}

            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
                margin: 0;
                padding: 0;
                background-color: var(--light-bg);
                color: var(--text-color);
                line-height: 1.6;
                display: flex;
                justify-content: center;
                align-items: flex-start;
                min-height: 100vh;
                overflow-x: hidden;
                box-sizing: border-box;
            }}

            #app {{
                width: 100%;
                max-width: 1000px;
                background: var(--panel-bg);
                border-radius: 16px;
                box-shadow: var(--shadow-medium);
                padding: 40px;
                margin: 40px 20px;
                box-sizing: border-box;
                display: flex;
                flex-direction: column;
                gap: 30px;
                transition: var(--transition-slow);
                min-height: 700px;
            }}

            h1 {{
                font-size: 2.2em;
                color: var(--primary-dark);
                text-align: center;
                margin-bottom: 30px;
                letter-spacing: -0.02em;
            }}

            h2 {{
                font-size: 1.6em;
                color: var(--primary-light);
                margin-top: 30px;
                margin-bottom: 15px;
            }}

            p {{
                margin-bottom: 1em;
            }}

            /* STATE 1: ENTRY */
            #entry-state {{
                display: flex;
                flex-direction: column;
                align-items: center;
                gap: 25px;
                text-align: center;
            }}

            #input-explanation {{
                width: 100%;
                min-height: 200px;
                padding: 20px;
                border: 2px solid var(--mid-bg);
                border-radius: 10px;
                font-size: 1.1em;
                resize: vertical;
                box-sizing: border-box;
                font-family: inherit;
                color: var(--text-color);
                transition: border-color 0.3s ease;
            }}

            #input-explanation:focus {{
                border-color: var(--accent-blue);
                outline: none;
            }}

            button {{
                padding: 15px 30px;
                border: none;
                border-radius: 8px;
                background-color: var(--accent-blue);
                color: white;
                font-size: 1.1em;
                cursor: pointer;
                transition: background-color 0.3s ease, transform 0.2s ease;
                box-shadow: var(--shadow-light);
                flex-shrink: 0; /* Prevent button from shrinking */
            }}

            button:hover {{
                background-color: #2980b9;
                transform: translateY(-2px);
            }}

            button:active {{
                transform: translateY(0);
            }}

            .small-button {{
                padding: 8px 15px;
                font-size: 0.9em;
                background-color: var(--primary-light);
            }}

            .small-button:hover {{
                background-color: var(--primary-dark);
            }}

            /* STATE 2: ACTIVE */
            #active-state, #result-state {{
                display: none; /* Initially hidden */
                opacity: 0;
                transition: opacity var(--transition-slow);
            }}

            .state-visible {{
                display: flex;
                flex-direction: column;
                gap: 20px;
                opacity: 1;
            }}

            .layout-columns {{
                display: flex;
                gap: 30px;
                flex-wrap: wrap; /* Allow wrapping on smaller screens */
            }}

            .main-content {{
                flex: 3;
                min-width: 300px;
            }

            .side-panel {{
                flex: 1;
                min-width: 250px;
                background-color: var(--mid-bg);
                border-radius: 12px;
                padding: 25px;
                box-shadow: var(--shadow-light);
            }}

            #editable-explanation {{
                background-color: var(--panel-bg);
                padding: 20px;
                border-radius: 10px;
                border: 1px solid var(--mid-bg);
                min-height: 180px;
                font-size: 1.1em;
                line-height: 1.8;
                cursor: text;
                white-space: pre-wrap;
                word-wrap: break-word;
                margin-bottom: 20px;
                position: relative;
            }

            #editable-explanation:focus {{
                outline: none;
                border-color: var(--accent-blue);
            }}

            .highlight {{
                background-color: var(--highlight-color);
                cursor: pointer;
                border-bottom: 1px dashed rgba(var(--primary-dark-rgb), 0.3);
                transition: background-color 0.2s ease;
            }}

            .highlight:hover {{
                background-color: rgba(var(--accent-blue-rgb), 0.2);
            }}

            #suggestions-panel {{
                position: fixed; /* Use fixed for overlay behavior */
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                background-color: var(--panel-bg);
                border-radius: 12px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.15);
                padding: 30px;
                width: 90%;
                max-width: 600px;
                z-index: 1000;
                display: none;
                flex-direction: column;
                gap: 15px;
                opacity: 0;
                transition: opacity 0.3s ease, transform 0.3s ease;
                border: 1px solid var(--mid-bg);
            }}

            #suggestions-panel.visible {{
                display: flex;
                opacity: 1;
                transform: translate(-50%, -50%) scale(1);
            }}

            #suggestions-panel h3 {{
                margin-top: 0;
                color: var(--primary-dark);
                font-size: 1.4em;
            }}

            #suggestions-panel .panel-section {{
                background-color: var(--mid-bg);
                padding: 15px;
                border-radius: 8px;
                font-size: 0.95em;
            }}
            #suggestions-panel .panel-section strong {{ color: var(--primary-light); }}

            #suggestions-panel textarea {{
                width: 100%;
                min-height: 80px;
                padding: 10px;
                border: 1px solid var(--primary-light);
                border-radius: 6px;
                font-family: inherit;
                font-size: 1em;
                resize: vertical;
                box-sizing: border-box;
            }}

            .panel-buttons {{
                display: flex;
                justify-content: flex-end;
                gap: 10px;
                margin-top: 15px;
            }}

            .panel-buttons button {{
                padding: 10px 20px;
                font-size: 0.95em;
                box-shadow: none;
            }}

            .panel-buttons .apply-btn {{ background-color: var(--accent-green); }}
            .panel-buttons .apply-btn:hover {{ background-color: #27ae60; }}
            .panel-buttons .edit-btn {{ background-color: var(--primary-light); }}
            .panel-buttons .edit-btn:hover {{ background-color: var(--primary-dark); }}
            .panel-buttons .ignore-btn {{ background-color: #95a5a6; }}
            .panel-buttons .ignore-btn:hover {{ background-color: #7f8c8d; }}

            #implications-list ul {{
                list-style: none;
                padding: 0;
            }}

            #implications-list li {{
                background-color: var(--panel-bg);
                padding: 12px 18px;
                margin-bottom: 8px;
                border-radius: 8px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.05);
                display: flex;
                align-items: center;
                gap: 10px;
                font-size: 0.95em;
            }}
            #implications-list li::before {{
                content: '•';
                color: var(--accent-blue);
                font-size: 1.2em;
                font-weight: bold;
            }}

            /* Clarity Meter (Rule 16: dynamic dial) */
            #clarity-meter-container {{
                display: flex;
                flex-direction: column;
                align-items: center;
                gap: 10px;
                margin-bottom: 20px;
            }}

            #clarity-meter-svg {{
                width: 120px;
                height: 120px;
                transform: rotate(-90deg); /* Start from the left */
            }}

            .meter-background {{
                stroke: var(--mid-bg);
                stroke-width: 10;
                fill: none;
            }}

            .meter-fill {{
                stroke: var(--accent-blue);
                stroke-width: 10;
                fill: none;
                transition: stroke-dasharray var(--transition-slow);
            }}

            .meter-text {{
                font-size: 1.8em;
                font-weight: bold;
                fill: var(--primary-dark);
                text-anchor: middle;
                transition: fill var(--transition-slow);
                transform: rotate(90deg); /* Counter-rotate text */
            }}

            /* STATE 3: RESULT */
            #final-clarified-text {{
                width: 100%;
                min-height: 250px;
                padding: 20px;
                border: 2px solid var(--mid-bg);
                border-radius: 10px;
                font-size: 1.1em;
                line-height: 1.8;
                resize: vertical;
                box-sizing: border-box;
                font-family: inherit;
                color: var(--text-color);
                background-color: var(--panel-bg);
            }}

            #final-implications {{
                background-color: var(--mid-bg);
                padding: 25px;
                border-radius: 12px;
            }}

            #final-implications h3 {{
                color: var(--primary-light);
                margin-top: 0;
            }}

            #final-implications ul {{
                list-style: disc inside;
                padding-left: 0;
            }}

            #final-implications li {{
                margin-bottom: 8px;
                font-size: 1em;
            }}

            .result-actions {{
                display: flex;
                justify-content: center;
                gap: 15px;
                margin-top: 30px;
            }}

            .result-actions button.secondary {{
                background-color: var(--primary-light);
            }}
            .result-actions button.secondary:hover {{
                background-color: var(--primary-dark);
            }}

            /* Side-by-Side Comparison */
            #side-by-side-comparison {{
                position: fixed;
                top: 0;
                left: 0;
                width: 100vw;
                height: 100vh;
                background-color: rgba(0, 0, 0, 0.7);
                display: none;
                justify-content: center;
                align-items: center;
                z-index: 2000;
                opacity: 0;
                transition: opacity 0.3s ease;
            }}

            #side-by-side-comparison.visible {{
                display: flex;
                opacity: 1;
            }}

            #comparison-content {{
                background-color: var(--panel-bg);
                border-radius: 16px;
                padding: 40px;
                box-shadow: var(--shadow-medium);
                display: flex;
                gap: 30px;
                max-width: 90%;
                max-height: 90%;
                overflow-y: auto;
                position: relative;
            }}

            #comparison-content .comparison-column {{
                flex: 1;
                min-width: 300px;
                display: flex;
                flex-direction: column;
            }}

            #comparison-content h3 {{
                color: var(--primary-dark);
                margin-top: 0;
                margin-bottom: 15px;
                text-align: center;
            }}

            #comparison-content pre {{
                background-color: var(--mid-bg);
                padding: 20px;
                border-radius: 10px;
                white-space: pre-wrap;
                word-wrap: break-word;
                flex-grow: 1;
                font-size: 1em;
                line-height: 1.7;
                border: 1px solid var(--mid-bg);
            }}

            #close-comparison {{
                position: absolute;
                top: 15px;
                right: 15px;
                background: none;
                border: none;
                font-size: 2em;
                color: var(--primary-light);
                cursor: pointer;
                transition: color 0.2s ease;
            }}
            #close-comparison:hover {{
                color: var(--primary-dark);
            }}

            /* Accessibility */
            [aria-hidden="true"] {{
                display: none !important;
            }}

            /* Responsive Adjustments */
            @media (max-width: 768px) {{
                #app {{
                    padding: 25px;
                    margin: 20px;
                }}
                h1 {{ font-size: 1.8em; }}
                h2 {{ font-size: 1.4em; }}
                .layout-columns {{
                    flex-direction: column;
                }}
                .side-panel {{
                    min-width: unset;
                    width: 100%;
                }}
                #suggestions-panel {{
                    width: 95%;
                    padding: 20px;
                }}
                #comparison-content {{
                    flex-direction: column;
                    gap: 20px;
                    padding: 25px;
                }}
                #comparison-content .comparison-column {{
                    min-width: unset;
                    width: 100%;
                }}
                .result-actions {{
                    flex-direction: column;
                    gap: 10px;
                }}
                button {{
                    width: 100%;
                }}
                .result-actions button {{
                     width: auto;
                }}
            }}
        </style>
    </head>
    <body>
        <div id="app">
            <h1>Clarity Flow Tracker: Explain Smarter</h1>

            <!-- State 1: Entry -->
            <div id="entry-state" class="state-visible">
                <textarea id="input-explanation" placeholder="Paste your technical explanation here.
Example: Our new blockchain-based distributed ledger solution utilizes a Byzantine Fault Tolerant consensus mechanism, specifically a PBFT variant, to ensure immutability and data integrity. This approach, while computationally intensive due to cryptographic hashing and inter-node validation, mitigates single points of failure and prevents Sybil attacks, ultimately providing an auditable, transparent, and secure record for supply chain provenance."></textarea>
                <button id="analyze-btn">Analyze Clarity</button>
            </div>

            <!-- State 2: Active -->
            <div id="active-state">
                <div id="clarity-meter-container">
                    <svg id="clarity-meter-svg" viewBox="0 0 100 100">
                        <circle class="meter-background" cx="50" cy="50" r="45"></circle>
                        <circle class="meter-fill" cx="50" cy="50" r="45" stroke-dasharray="0 282.74"></circle>
                        <text class="meter-text" x="50" y="50" alignment-baseline="middle" dominant-baseline="central">0%</text>
                    </svg>
                    <p style="font-size:1.1em; color: var(--primary-light);">Current Clarity Score</p>
                </div>

                <div class="layout-columns">
                    <div class="main-content">
                        <h2>Your Explanation (Click highlighted parts to simplify)</h2>
                        <div id="editable-explanation" contenteditable="true" spellcheck="false"></div>
                    </div>
                    <div class="side-panel">
                        <h2>Detected Implications</h2>
                        <div id="implications-list">
                            <ul></ul>
                        </div>
                    </div>
                </div>
                <div style="display: flex; justify-content: flex-end; margin-top: 20px;">
                    <button id="finish-analysis-btn">Finish Analysis</button>
                </div>
            </div>

            <!-- Suggestion Panel (Overlay) -->
            <div id="suggestions-panel" aria-hidden="true">
                <h3>Simplify Segment</h3>
                <div class="panel-section">
                    <strong>Original:</strong> <span id="original-segment-text"></span>
                </div>
                <div class="panel-section">
                    <strong>Proposed Rewrite:</strong>
                    <textarea id="proposed-rewrite-text"></textarea>
                </div>
                <div class="panel-section">
                    <strong>Why this suggestion helps:</strong> <span id="suggestion-explanation"></span>
                </div>
                <div class="panel-buttons">
                    <button class="ignore-btn" id="ignore-suggestion-btn">Ignore</button>
                    <button class="edit-btn" id="edit-suggestion-btn">Edit</button>
                    <button class="apply-btn" id="apply-suggestion-btn">Apply</button>
                </div>
            </div>

            <!-- State 3: Result -->
            <div id="result-state">
                <div id="clarity-meter-container">
                    <svg id="final-clarity-meter-svg" viewBox="0 0 100 100">
                        <circle class="meter-background" cx="50" cy="50" r="45"></circle>
                        <circle class="meter-fill" cx="50" cy="50" r="45" stroke-dasharray="0 282.74"></circle>
                        <text class="meter-text" x="50" y="50" alignment-baseline="middle" dominant-baseline="central">0%</text>
                    </svg>
                    <p style="font-size:1.1em; color: var(--primary-dark);">Final Clarity Score</p>
                </div>

                <h2>Your Clarified Explanation</h2>
                <textarea id="final-clarified-text" readonly></textarea>

                <h2>Core Implications</h2>
                <div id="final-implications">
                    <ul></ul>
                </div>

                <div class="result-actions">
                    <button id="copy-clarified-btn">Copy Clarified Text</button>
                    <button class="secondary" id="view-comparison-btn">View Side-by-Side Comparison</button>
                    <button class="small-button" id="start-new-analysis-btn" style="margin-left: auto;">Start New Analysis</button>
                </div>
            </div>
        </div>

        <!-- Side-by-Side Comparison Overlay -->
        <div id="side-by-side-comparison" aria-hidden="true">
            <div id="comparison-content">
                <button id="close-comparison">×</button>
                <div class="comparison-column">
                    <h3>Original Text</h3>
                    <pre id="original-comparison-text"></pre>
                </div>
                <div class="comparison-column">
                    <h3>Revised Text</h3>
                    <pre id="revised-comparison-text"></pre>
                </div>
            </div>
        </div>

        <script>
            // Ensure primary-dark-rgb and accent-blue-rgb are available for JS styling
            document.documentElement.style.setProperty('--primary-dark-rgb', '44, 62, 80');
            document.documentElement.style.setProperty('--accent-blue-rgb', '52, 152, 219');

            const initialText = `{escaped_text}`;
            const jargonData = {jargon_json};
            const initialImplications = {implications_json};

            const app = document.getElementById('app');
            const entryState = document.getElementById('entry-state');
            const activeState = document.getElementById('active-state');
            const resultState = document.getElementById('result-state');
            const analyzeBtn = document.getElementById('analyze-btn');
            const inputExplanation = document.getElementById('input-explanation');
            const editableExplanation = document.getElementById('editable-explanation');
            const implicationsList = document.querySelector('#implications-list ul');
            const clarityMeterSvg = document.getElementById('clarity-meter-svg');
            const finalClarityMeterSvg = document.getElementById('final-clarity-meter-svg');
            const finishAnalysisBtn = document.getElementById('finish-analysis-btn');

            const suggestionsPanel = document.getElementById('suggestions-panel');
            const originalSegmentText = document.getElementById('original-segment-text');
            const proposedRewriteText = document.getElementById('proposed-rewrite-text');
            const suggestionExplanation = document.getElementById('suggestion-explanation');
            const applySuggestionBtn = document.getElementById('apply-suggestion-btn');
            const editSuggestionBtn = document.getElementById('edit-suggestion-btn');
            const ignoreSuggestionBtn = document.getElementById('ignore-suggestion-btn');

            const finalClarifiedText = document.getElementById('final-clarified-text');
            const finalImplicationsList = document.querySelector('#final-implications ul');
            const copyClarifiedBtn = document.getElementById('copy-clarified-btn');
            const viewComparisonBtn = document.getElementById('view-comparison-btn');
            const startNewAnalysisBtn = document.getElementById('start-new-analysis-btn');

            const sideBySideComparison = document.getElementById('side-by-side-comparison');
            const originalComparisonText = document.getElementById('original-comparison-text');
            const revisedComparisonText = document.getElementById('revised-comparison-text');
            const closeComparisonBtn = document.getElementById('close-comparison');

            let currentClarityScore = 0;
            let totalJargonCount = 0;
            let appliedSuggestionCount = 0;
            let activeSegmentSpan = null; // To keep track of the currently clicked jargon span
            let processedTextContent = ''; // Holds the current state of the text in editableExplanation
            let currentImplications = [];

            // Helper to update SVG meter
            function updateClarityMeter(score, svgElement) {
                const circle = svgElement.querySelector('.meter-fill');
                const text = svgElement.querySelector('.meter-text');
                const circumference = 2 * Math.PI * 45; // r=45
                const offset = circumference - (score / 100) * circumference;
                circle.style.strokeDasharray = `${circumference - offset} ${offset}`;
                text.textContent = `${Math.round(score)}%`;
                
                // Color change based on score (optional, but adds dynamism)
                if (score < 40) {
                    circle.style.stroke = '#e74c3c'; // Red
                    text.style.fill = '#e74c3c';
                } else if (score < 70) {
                    circle.style.stroke = '#f1c40f'; // Yellow
                    text.style.fill = '#f1c40f';
                } else {
                    circle.style.stroke = var('--accent-green'); // Green
                    text.style.fill = var('--accent-green');
                }
            }

            function animateClarityMeter(finalScore, duration = 1500, svgElement) {
                let startScore = currentClarityScore;
                let startTime = null;

                function animate(currentTime) {
                    if (!startTime) startTime = currentTime;
                    const progress = (currentTime - startTime) / duration;
                    const animatedScore = startScore + (finalScore - startScore) * Math.min(progress, 1);
                    updateClarityMeter(animatedScore, svgElement);
                    if (progress < 1) {
                        requestAnimationFrame(animate);
                    } else {
                        currentClarityScore = finalScore;
                    }
                }
                requestAnimationFrame(animate);
            }

            function updateImplications(implications) {
                implicationsList.innerHTML = '';
                finalImplicationsList.innerHTML = ''; // Keep final list updated too
                implications.forEach(imp => {
                    const li = document.createElement('li');
                    li.textContent = imp;
                    implicationsList.appendChild(li);

                    const liFinal = document.createElement('li');
                    liFinal.textContent = imp;
                    finalImplicationsList.appendChild(liFinal);
                });
                currentImplications = implications;
            }

            function calculateClarityScore() {
                if (totalJargonCount === 0) return 100; // No jargon, perfect score
                return Math.min(100, (30 + (appliedSuggestionCount / totalJargonCount) * 70)); // Base score + bonus for applying suggestions
            }

            function highlightText(text) {
                let highlightedText = text;
                totalJargonCount = 0;
                const jargonEntries = Object.entries(jargonData);

                // Sort jargon phrases by length (descending) to prevent partial matches
                jargonEntries.sort((a, b) => b[0].length - a[0].length);

                for (const [jargon, data] of jargonEntries) {
                    const regex = new RegExp(re.escape(jargon), 'g');
                    highlightedText = highlightedText.replace(regex, (match) => {
                        totalJargonCount++;
                        return `<span class="highlight" data-jargon="${html.escape(jargon)}">${match}</span>`;
                    });
                }
                return highlightedText;
            }

            function transitionState(fromState, toState) {
                fromState.classList.remove('state-visible');
                fromState.style.opacity = '0';
                setTimeout(() => {
                    fromState.style.display = 'none';
                    toState.style.display = 'flex';
                    // Trigger reflow to ensure transition plays
                    toState.offsetHeight; 
                    toState.classList.add('state-visible');
                    // Special handling for the result state to set final score
                    if (toState === resultState) {
                        animateClarityMeter(calculateClarityScore(), 1000, finalClarityMeterSvg);
                    }
                }, 400); // Duration matches --transition-slow
            }

            // Initial setup for the entry state
            inputExplanation.value = initialText;
            updateImplications(initialImplications); // Populate initial implications

            // Event Listeners
            analyzeBtn.addEventListener('click', () => {
                const textToAnalyze = inputExplanation.value.trim();
                if (textToAnalyze.length < 20) {
                     alert("Please provide a more substantial technical explanation (at least 20 words) for analysis.");
                     return;
                }
                processedTextContent = textToAnalyze;
                editableExplanation.innerHTML = highlightText(textToAnalyze);
                currentClarityScore = calculateClarityScore();
                animateClarityMeter(currentClarityScore, 1000, clarityMeterSvg);
                transitionState(entryState, activeState);
                editableExplanation.focus();
            });

            editableExplanation.addEventListener('click', (event) => {
                const target = event.target;
                if (target.classList.contains('highlight')) {
                    activeSegmentSpan = target;
                    const jargon = target.dataset.jargon;
                    const data = jargonData[jargon];

                    originalSegmentText.textContent = jargon;
                    proposedRewriteText.value = data.rewrite;
                    suggestionExplanation.textContent = data.explanation;
                    suggestionsPanel.classList.add('visible');
                    suggestionsPanel.setAttribute('aria-hidden', 'false');
                }
            });

            applySuggestionBtn.addEventListener('click', () => {
                if (activeSegmentSpan) {
                    const originalJargon = activeSegmentSpan.dataset.jargon;
                    const newText = proposedRewriteText.value;
                    const fullText = editableExplanation.textContent; // Get the raw text
                    // Replace only the occurrence of the segment being edited
                    // This is a simplified replacement. A more robust solution might use Range objects.
                    const newHighlightedContent = editableExplanation.innerHTML.replace(
                        `<span class="highlight" data-jargon="${html.escape(originalJargon)}">${originalJargon}</span>`,
                        `<span>${html.escape(newText)}</span>`
                    );
                    editableExplanation.innerHTML = newHighlightedContent;
                    processedTextContent = editableExplanation.textContent; // Update stored content
                    activeSegmentSpan.classList.remove('highlight');
                    activeSegmentSpan.removeAttribute('data-jargon');
                    
                    // Update score
                    appliedSuggestionCount++;
                    const newScore = calculateClarityScore();
                    animateClarityMeter(newScore, 500, clarityMeterSvg);
                }
                suggestionsPanel.classList.remove('visible');
                suggestionsPanel.setAttribute('aria-hidden', 'true');
            });

            editSuggestionBtn.addEventListener('click', () => {
                proposedRewriteText.focus();
            });

            ignoreSuggestionBtn.addEventListener('click', () => {
                if (activeSegmentSpan) {
                    activeSegmentSpan.classList.remove('highlight');
                    activeSegmentSpan.style.borderBottom = 'none'; // Remove dashed line
                    activeSegmentSpan.style.backgroundColor = 'transparent'; // Remove background highlight
                    activeSegmentSpan.removeAttribute('data-jargon'); // Remove data attribute so it's not re-highlighted
                    activeSegmentSpan = null; // Clear active segment
                }
                suggestionsPanel.classList.remove('visible');
                suggestionsPanel.setAttribute('aria-hidden', 'true');
            });
            
            finishAnalysisBtn.addEventListener('click', () => {
                finalClarifiedText.value = editableExplanation.textContent; // Get final text from contenteditable
                originalComparisonText.textContent = initialText;
                revisedComparisonText.textContent = editableExplanation.textContent;
                transitionState(activeState, resultState);
            });

            copyClarifiedBtn.addEventListener('click', () => {
                navigator.clipboard.writeText(finalClarifiedText.value).then(() => {
                    alert('Clarified text copied to clipboard!');
                }).catch(err => {
                    console.error('Failed to copy text: ', err);
                });
            });

            viewComparisonBtn.addEventListener('click', () => {
                sideBySideComparison.classList.add('visible');
                sideBySideComparison.setAttribute('aria-hidden', 'false');
            });

            closeComparisonBtn.addEventListener('click', () => {
                sideBySideComparison.classList.remove('visible');
                sideBySideComparison.setAttribute('aria-hidden', 'true');
            });

            startNewAnalysisBtn.addEventListener('click', () => {
                // Reset state variables
                currentClarityScore = 0;
                totalJargonCount = 0;
                appliedSuggestionCount = 0;
                activeSegmentSpan = null;
                processedTextContent = '';

                // Clear text areas and lists
                inputExplanation.value = '';
                editableExplanation.innerHTML = '';
                finalClarifiedText.value = '';
                implicationsList.innerHTML = '';
                finalImplicationsList.innerHTML = '';
                originalComparisonText.textContent = '';
                revisedComparisonText.textContent = '';

                // Reset meter visuals
                updateClarityMeter(0, clarityMeterSvg);
                updateClarityMeter(0, finalClarityMeterSvg);

                // Reset implications to initial example (or clear if dynamic)
                updateImplications(initialImplications);
                
                transitionState(resultState, entryState);
                inputExplanation.focus();
            });

            // Set initial input text in entry state (from Python)
            inputExplanation.value = initialText;
            inputExplanation.focus();
        </script>
    </body>
    </html>
    """
    return html_content

def _cli_main():
    """
    Placeholder for command-line execution, though this tool is designed for browser interaction.
    """
    print("This tool is designed to run in a browser environment (Mode 3).")
    print("Paste your technical explanation into the input field in the browser.")
    print("Example usage:\n")
    test_input = "Our new blockchain-based distributed ledger solution utilizes a Byzantine Fault Tolerant consensus mechanism, specifically a PBFT variant, to ensure immutability and data integrity. This approach, while computationally intensive due to cryptographic hashing and inter-node validation, mitigates single points of failure and prevents Sybil attacks, ultimately providing an auditable, transparent, and secure record for supply chain provenance."
    print("--- Generated HTML (truncated for CLI display) ---\n")
    print(process(test_input)[:500] + "\n...") # Show first 500 chars of HTML
    print("\nOpen this HTML content in a browser to use the interactive tool.")


_browser_input = globals().get('USER_INPUT', None)
if _browser_input is not None:
    print(process(_browser_input))
elif __name__ == "__main__":
    import sys
    # SAFE_SYS_ARGV_USAGE: only modify sys.argv if run directly
    sys.argv = ['tool'] # Mock sys.argv if needed, though not directly used by this _cli_main
    _cli_main()